name: E2E Tests
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
    types: [opened, synchronize, reopened]

concurrency:
  group: e2e-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    name: Frontend E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci
        env:
          NODE_ENV: production

      - name: Rebuild native modules & install required platform-specific packages
        run: |
          npm rebuild
          npm ls @rollup/rollup-linux-x64-gnu || npm install @rollup/rollup-linux-x64-gnu
          npm ls @swc/core-linux-x64-gnu || npm install @swc/core-linux-x64-gnu
      
      - name: Cypress run (excluding cache tests and scraping-dependent tests)
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev:fe
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 120
          browser: chrome
          config-file: frontend/cypress.config.cjs
          record: false
          install: false
          spec: 'frontend/cypress/e2e/browser-navigation.cy.ts,frontend/cypress/e2e/home.cy.ts,frontend/cypress/e2e/keyboard-navigation.cy.ts,frontend/cypress/e2e/lazy-loading.cy.ts,frontend/cypress/e2e/song-card-keyboard.cy.ts,frontend/cypress/e2e/song-card.cy.ts,frontend/cypress/e2e/tab-navigation.cy.ts,frontend/cypress/e2e/theme.cy.ts,frontend/cypress/e2e/artist-search/**/*.cy.ts'
        env:
          NODE_OPTIONS: "--experimental-vm-modules"
      
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4.6.2
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
          
      - name: Upload videos
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: cypress-videos
          path: frontend/cypress/videos

  visual-testing:
    name: Visual Testing & PR Comments
    runs-on: ubuntu-latest
    needs: e2e
    if: github.event_name == 'pull_request' && failure()
    permissions:
      contents: write
      pull-requests: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check if cypress-screenshots artifact exists
        id: check-artifact
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });
            return artifacts.data.artifacts.some(artifact => artifact.name === 'cypress-screenshots');

      - name: Download test artifacts
        if: steps.check-artifact.outputs.result == 'true'
        uses: actions/download-artifact@v4.3.0
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
          
      - name: Comment test failures on PR
        if: steps.check-artifact.outputs.result == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            
            const screenshotDir = 'frontend/cypress/screenshots';
            let comment = '## 🧪 E2E Test Failures\n\n';
            
            if (fs.existsSync(screenshotDir)) {
              const files = fs.readdirSync(screenshotDir);
              if (files.length > 0) {
                comment += 'E2E tests failed. Screenshots have been uploaded as artifacts.\n\n';
                comment += '**Failed tests:**\n';
                files.forEach(file => {
                  if (!file.includes('cache') && !file.includes('song-search')) {
                    comment += `- ${file}\n`;
                  }
                });
                comment += '\n💡 **Tip:** These tests cover general application functionality excluding cache-specific features and scraping-dependent tests.\n';
              } else {
                comment += 'E2E tests failed but no screenshots were captured.\n';
              }
            } else {
              comment += 'E2E tests failed but no screenshot directory found.\n';
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            }); 