services:
  - type: web
    name: chordium-backend
    env: node
    plan: free
    buildCommand: ./render-build.sh
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true 