services:
  - type: web
    name: chordium-backend
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CI
        value: "true"
      - key: NODE_VERSION
        value: "20"
    healthCheckPath: /health
    autoDeploy: true 