name: Backend Tests
# Runs backend unit tests (Jest) when backend files or shared dependencies change
# Includes logger utility and comprehensive S3 caching functionality tests
on:
  push:
    branches: ["*"]
    paths:
      - 'backend/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/backend-tests.yml'
      - 'shared/**'
  pull_request:
    branches: ["*"]
    paths:
      - 'backend/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/backend-tests.yml'
      - 'shared/**'
    types: [opened, synchronize, reopened]

concurrency:
  group: backend-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json
            backend/package-lock.json

      - name: Install dependencies
        run: npm ci --verbose
        env:
          NODE_ENV: production

      - name: Run backend unit tests
        run: npm run test:be
        env:
          SUPABASE_URL: "http://localhost:54321/mock"
          SUPABASE_SERVICE_ROLE_KEY: "dummy-key"
          # Mock AWS credentials for testing (these don't need to be real)
          AWS_ACCESS_KEY_ID: mock-access-key
          AWS_SECRET_ACCESS_KEY: mock-secret-key
          AWS_REGION: eu-central-1
          S3_BUCKET_NAME: test-bucket

      - name: Upload backend test coverage
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: backend-test-coverage
          path: backend/coverage/
          retention-days: 7
