name: Backend Build & Lint
# Builds and lints backend when backend files or shared dependencies change
on:
  push:
    branches: ["*"]
    paths:
      - 'backend/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/backend-build.yml'
      - 'shared/**'
  pull_request:
    branches: ["*"]
    paths:
      - 'backend/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/backend-build.yml'
      - 'shared/**'
    types: [opened, synchronize, reopened]

concurrency:
  group: backend-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-build:
    name: Backend Build & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json


      - name: Install dependencies
        run: npm ci --verbose
        env:
          NODE_ENV: production

      - name: Debug Dependencies and Workspaces
        run: |
          echo "=== Root package.json workspaces ==="
          cat package.json | grep -A 5 "workspaces"
          echo ""
          echo "=== Checking workspace dependency resolution ==="
          npm ls jest ts-jest @types/express @types/cors @types/jest || echo "Some packages not found in root"
          echo ""
          echo "=== Backend workspace dependency check ==="
          cd backend && npm ls jest ts-jest @types/express @types/cors @types/jest || echo "Some packages not found in backend"
          echo ""
          echo "=== Node modules structure ==="
          echo "Root node_modules/@types:" && ls -l node_modules/@types 2>/dev/null || echo "Not found"
          echo "Backend node_modules/@types:" && ls -l backend/node_modules/@types 2>/dev/null || echo "Not found"
          echo "Root node_modules/jest:" && ls -l node_modules/jest/package.json 2>/dev/null || echo "Not found"
          echo "Backend node_modules/jest:" && ls -l backend/node_modules/jest/package.json 2>/dev/null || echo "Not found"

      - name: Lint backend
        run: npm run lint:be
        continue-on-error: true

      - name: Build backend
        run: npm run build:be

      - name: Upload backend build artifacts
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: backend-build
          path: backend/dist/
          retention-days: 7
