name: Backend Build & Lint
# Builds and lints backend when backend files or shared dependencies change
on:
  push:
    branches: ["*"]
    paths:
      - 'backend/**'
      - 'packages/types/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/backend-build.yml'
      - 'shared/fixtures/**'
  pull_request:
    branches: ["*"]
    paths:
      - 'backend/**'
      - 'packages/types/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/backend-build.yml'
      - 'shared/fixtures/**'
    types: [opened, synchronize, reopened]

concurrency:
  group: backend-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-build:
    name: Backend Build & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install root dependencies
        run: npm ci

      - name: Build backend using Turborepo
        run: npx turbo build --filter=chordium-backend

      - name: Lint backend using Turborepo
        run: npx turbo lint --filter=chordium-backend
        continue-on-error: true

      - name: Upload backend build artifacts
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: backend-build
          path: ./backend/dist/
          retention-days: 7
