name: Build & Lint
# Builds and lints both frontend and backend in a monorepo setup
# Uses workspace commands: npm run build:fe, npm run build:be, npm run lint
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
    types: [opened, synchronize, reopened]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json
            backend/package-lock.json

      - name: Install dependencies
        run: npm ci --verbose
        env:
          NODE_ENV: production

      - name: Rebuild native modules & install required platform-specific packages
        run: |
          npm rebuild
          npm ls @rollup/rollup-linux-x64-gnu || npm install @rollup/rollup-linux-x64-gnu
          npm ls @swc/core-linux-x64-gnu || npm install @swc/core-linux-x64-gnu

      - name: Lint frontend and backend
        run: npm run lint

      - name: Build frontend
        run: npm run build:fe

      - name: Build backend
        run: npm run build:be

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: frontend-build
          path: frontend/dist/
          retention-days: 7

      - name: Upload backend build artifacts
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: backend-build
          path: backend/dist/
          retention-days: 7 