name: Frontend Build & Lint
# Builds and lints frontend when frontend files or shared dependencies change
on:
  push:
    branches: ["*"]
    paths:
      - 'frontend/**'
      - 'packages/types/**'
      - 'package.json'
      - 'package-lock.json'
      - 'turbo.json'
      - '.github/workflows/frontend-build.yml'
      - 'shared/fixtures/**'
  pull_request:
    branches: ["*"]
    paths:
      - 'frontend/**'
      - 'packages/types/**'
      - 'package.json'
      - 'package-lock.json'
      - 'turbo.json'
      - '.github/workflows/frontend-build.yml'
      - 'shared/fixtures/**'

concurrency:
  group: frontend-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-build:
    name: Frontend Build & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install root dependencies
        run: npm ci --silent

      - name: Build types package first
        run: npx turbo build --filter=@chordium/types

      - name: Fix Rollup optional dependencies in CI
        run: |
          cd frontend
          # Try to install the missing platform-specific rollup binary
          npm install @rollup/rollup-linux-x64-gnu --no-save --silent || true
          # Alternative: force reinstall rollup entirely
          npm install rollup --force --silent || true
        
      - name: Build frontend using Turborepo
        run: npx turbo build --filter=chordium-frontend

      - name: Lint frontend using Turborepo
        run: npx turbo lint --filter=chordium-frontend --silent
        continue-on-error: true

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: frontend-build
          path: ./frontend/dist/
          retention-days: 7
