name: Frontend Tests
# Runs frontend unit tests (Vitest) when frontend files or shared dependencies change
# Includes utils, cache, metadata extraction, session storage tests
on:
  push:
    branches: ["*"]
    paths:
      - 'frontend/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/frontend-tests.yml'
      - 'shared/fixtures/**'
  pull_request:
    branches: ["*"]
    paths:
      - 'frontend/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/frontend-tests.yml'
      - 'shared/fixtures/**'
    types: [opened, synchronize, reopened]

concurrency:
  group: frontend-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-tests:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --verbose

      - name: Rebuild native modules & install required platform-specific packages
        run: |
          npm rebuild
          npm ls @rollup/rollup-linux-x64-gnu || npm install @rollup/rollup-linux-x64-gnu
          npm ls @swc/core-linux-x64-gnu || npm install @swc/core-linux-x64-gnu

      - name: Run frontend unit tests
        run: npm run test:fe

      - name: Upload frontend test coverage
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: frontend-test-coverage
          path: frontend/coverage/
          retention-days: 7
