name: Frontend Build & Lint
# Builds and lints frontend when frontend files or shared dependencies change
on:
  push:
    branches: ["*"]
    paths:
      - 'frontend/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/frontend-build.yml'
      - 'shared/fixtures/**'
  pull_request:
    branches: ["*"]
    paths:
      - 'frontend/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/frontend-build.yml'
      - 'shared/fixtures/**'
    types: [opened, synchronize, reopened]

concurrency:
  group: frontend-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-build:
    name: Frontend Build & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install root dependencies
        run: npm ci --silent

      - name: Clean and reinstall frontend dependencies with platform-specific packages
        run: |
          cd frontend
          rm -rf node_modules package-lock.json
          npm install --silent
          # Force install platform-specific Rollup binaries
          npm install @rollup/rollup-linux-x64-gnu --save-dev --silent || true
        
      - name: Build frontend using Turborepo
        run: npx turbo build --filter=chordium-frontend

      - name: Lint frontend using Turborepo
        run: npx turbo lint --filter=chordium-frontend --silent
        continue-on-error: true

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: frontend-build
          path: ./frontend/dist/
          retention-days: 7
