name: PR Approval Check
on:
  workflow_run:
    workflows: ["PR Approval Trigger"]
    types:
      - completed

jobs:
  check-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Mark visual changes as approved
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.workflow_run.pull_requests[0].number;
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Visual UI Testing Approval',
              head_sha: pullRequest.head.sha,
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'Visual changes approved',
                summary: 'The visual changes in this PR have been approved.'
              }
            });
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: ['visual-changes-approved']
            });
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: '✅ Visual changes have been approved. This PR can now be merged.'
            });
