name: PR Approval Trigger
on:
  issue_comment:
    types: [created]

jobs:
  trigger-approval:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'Approve visual changes')
    permissions:
        contents: write
        actions: write
    steps:
      - name: Trigger PR Approval Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: workflow } = await github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const approvalWorkflow = workflow.workflows.find(w => w.name === 'PR Approval Check');
            if (!approvalWorkflow) {
              throw new Error('Approval workflow not found');
            }
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: approvalWorkflow.id,
              ref: context.payload.issue.pull_request.head.ref
            });